version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: prismify-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: prismify
      POSTGRES_USER: profile
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U profile -d prismify"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local 